name: bearer service worker for Mastercard BackBank for Vaumoney of Vaults.biz
on:
  release:
    types:
      - published
  push:
    branches:
      - maintenance
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #main
      
      - name: Navigate to repo
        run: cd $GITHUB_WORKSPACE
          
      - name: Publish # https://github.com/cloudflare/wrangler-action/issues/76#issuecomment-1139761919
        uses: cloudflare/wrangler-action@2.0.0
        with:
          # email: "nmcarducci@gmail.com"
          apiToken: ${{ secrets.CF_API_TOKEN }}
          # Wrangler v2 does not support using the API Key.
          #apiKey: ${{ secrets.CF_API_KEY }} # You should instead use an API token.
          # apiToken: ${{ secrets.CF_API_TOKEN }} # https://superuser.com/questions/1575061/how-do-i-download-and-extract-a-tar-in-one-command-while-extracting-only-a-sing
          # preCommands: curl https://sh.rustup.rs -sSf | sh -s -- -y && PATH="$PATH:$HOME/.cargo/bin" && cargo install --git https://github.com/cloudflare/workers-rs && cargo install --git https://github.com/cloudflare/workers-rs --branch zeb/esbuild && PATH="$PATH:$HOME/.cache/.wasm-pack/.wasm-bindgen-cargo-install-0.2.81/bin" && curl -L 'https://github.com/WebAssembly/binaryen/releases/download/version_90/binaryen-version_90-x86-linux.tar.gz' | tar  -xz # && PATH="$PATH:$HOME/.cargo/bin" # --branch zeb/esbuild
          # command: "CF_CF_API_KEY: ${{ secrets.CF_API_KEY }} wrangler dev"
          # preCommands: npm install
          # command: publish --env production
          environment: "production"
          wranglerVersion: '2.0.24'
        env:
          USER: root
